name: bc
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconductor-edger=4.8.2
  - bioconductor-limma=3.66.0
  - matplotlib
  - numpy
  - openpyxl
  - pandas
  - pip
  - pyarrow
  - python=3.11
  - pytest
  - pyyaml
  - r-base=4.5.3
  - r-statmod=1.5.2
  - scikit-learn
  - scipy
  - statsmodels
