"""Tests for the GSE245601 preprocessing + malignant-cell-identification
phase (scripts/analysis/gse245601_0{1,2,3,4,5,6,7,8}_*.R).

These tests validate the R pipeline's *outputs* (the frozen TSV tables
under results/tables/) and the pipeline *source code* (structural,
candidate-blindness, and scope-boundary checks) -- they do not re-run the
R/Seurat/InferCNV pipeline itself (that is a multi-hour compute job with
its own gitignored intermediates under data/processed/gse245601/).

Tests that require an output table not yet present (because the R
pipeline has not finished running in this environment) are skipped, not
failed -- this file is designed to be run both mid-pipeline and after
full completion.
"""

from pathlib import Path

import pandas as pd
import pytest
import yaml

REPO_ROOT = Path(__file__).parent.parent
CONFIG_PATH = REPO_ROOT / "config" / "config.yaml"
SCRIPTS_DIR = REPO_ROOT / "scripts" / "analysis"
TABLES_DIR = REPO_ROOT / "results" / "tables"

CANDIDATE_GENES = [
    "USP34", "CTDNEP1", "EIF4ENIF1", "HMGB1", "KDM1A", "PET117", "TADA2B",
    "VEZF1", "ICK", "SUPT4H1", "TLK2", "TSR3", "USP17L29",
]
ALL_CANDIDATE_TERMS = CANDIDATE_GENES + ["PAICS"]


def _table(name: str) -> pd.DataFrame:
    path = TABLES_DIR / name
    if not path.exists():
        pytest.skip(f"{name} not yet generated by the R pipeline")
    sep = "\t"
    return pd.read_csv(path, sep=sep, compression="infer")


def _script_source(name: str) -> str:
    path = SCRIPTS_DIR / name
    assert path.exists(), f"expected pipeline script {name} not found"
    return path.read_text()


def _code_lines(name: str) -> list[str]:
    """Lines of an R script with full-line comments (lines whose first
    non-whitespace character is '#') stripped out, so candidate-gene
    mentions in explanatory doc-comments don't trigger blindness checks
    meant to catch actual code usage."""
    return [line for line in _script_source(name).splitlines() if not line.strip().startswith("#")]


def _block_between(code_lines: list[str], start_marker: str, end_line_stripped: str) -> str:
    start = next(i for i, l in enumerate(code_lines) if start_marker in l)
    end = next(i for i, l in enumerate(code_lines[start:], start) if l.strip() == end_line_stripped)
    return "\n".join(code_lines[start : end + 1])


# --- Candidate-blindness: structural checks on the R source itself ----------


class TestCandidateBlindness:
    @pytest.mark.parametrize(
        "script_name",
        [
            "gse245601_01_import_qc_doublets.R",
            "gse245601_02_normalize_cluster.R",
            "gse245601_03_annotate_celltypes.R",
            "gse245601_04_gene_order_file.R",
            "gse245601_05_infercnv_malignant.R",
            "gse245601_06_copykat_sensitivity.R",
            "gse245601_07_freeze_metadata.R",
            "gse245601_08_qc_figures.R",
        ],
    )
    def test_qc_and_annotation_scripts_never_reference_candidate_genes_as_values(self, script_name):
        code_lines = _code_lines(script_name)
        # Candidate gene symbols may legitimately appear in comments (the
        # docstring header explaining the blinding rule) or in an explicit
        # `stopifnot(!any(... %in% candidate_genes))`-style safety check
        # (script 03) -- but never as a quoted literal fed into a
        # marker/feature/filter/reference value on any other line.
        for line in code_lines:
            if "candidate_genes" in line or "ALL_CANDIDATE_TERMS" in line:
                continue  # the safety-check list itself, not a marker/feature use
            for gene in ALL_CANDIDATE_TERMS:
                for quote in ('"' + gene + '"', "'" + gene + "'"):
                    assert quote not in line, f"{script_name}: {line!r} references candidate gene {gene!r}"

    def test_annotation_marker_sets_exclude_all_candidates(self):
        code_lines = _code_lines("gse245601_03_annotate_celltypes.R")
        marker_block = _block_between(code_lines, "marker_sets <- list(", ")")
        for gene in ALL_CANDIDATE_TERMS:
            assert gene not in marker_block, f"marker_sets block references candidate gene {gene!r}"

    def test_script_03_explicitly_asserts_candidate_blindness(self):
        source = _script_source("gse245601_03_annotate_celltypes.R")
        assert "candidate_genes" in source
        assert "stopifnot" in source

    def test_infercnv_reference_selection_does_not_reference_candidates(self):
        code_lines = _code_lines("gse245601_05_infercnv_malignant.R")
        for line in code_lines:
            for gene in ALL_CANDIDATE_TERMS:
                assert gene not in line, f"{line!r} references candidate gene {gene!r}"

    def test_pseudobulk_scripts_are_preceded_by_a_frozen_written_design(self):
        """This test previously asserted NO pseudobulk/DE script existed
        yet -- a deliberate gate preventing premature aggregation before
        the statistical design was frozen. That gate has since been
        opened legitimately: gse245601_PREANALYSIS.md section 13 records
        the two-track (Track A / Track B) pseudobulk design, frozen in
        writing before any pseudobulk aggregation or candidate-gene
        expression was inspected (see that section's own audit-first
        ordering). What this test now checks is that the written freeze
        exists and precedes/accompanies the pseudobulk scripts -- the gate
        was passed through, not skipped."""
        existing_scripts = [p.name.lower() for p in SCRIPTS_DIR.glob("gse245601_*.R")]
        has_pseudobulk_script = any("pseudobulk" in name or "edger" in name for name in existing_scripts)
        if not has_pseudobulk_script:
            pytest.skip("no pseudobulk/edgeR script present in this checkout yet -- gate still closed, nothing to check")

        preanalysis_path = REPO_ROOT / "docs" / "gse245601_PREANALYSIS.md"
        assert preanalysis_path.exists(), "pseudobulk script(s) exist but gse245601_PREANALYSIS.md is missing"
        source = preanalysis_path.read_text()
        assert "section 13" in source.lower() or "## 13." in source
        assert "Track A" in source and "Track B" in source
        assert "frozen" in source.lower()


class TestQCTreatmentBlindness:
    def test_qc_thresholds_are_not_conditioned_on_treatment(self):
        source = _script_source("gse245601_01_import_qc_doublets.R")
        # The QC keep-mask must reference only nCount_RNA/nFeature_RNA/percent.mt,
        # never `condition` or `Tamoxifen`/`Control` as part of the filter itself.
        keep_line = [line for line in source.splitlines() if "keep <-" in line]
        assert len(keep_line) == 1
        assert "condition" not in keep_line[0]
        assert "Tamoxifen" not in keep_line[0]
        assert "Control" not in keep_line[0]

    def test_frozen_qc_thresholds_match_preanalysis_document(self):
        source = _script_source("gse245601_01_import_qc_doublets.R")
        assert "QC_MIN_NCOUNT <- 5000" in source
        assert "QC_MIN_NFEATURE <- 2000" in source
        assert "QC_MAX_PERCENT_MT <- 25" in source

    def test_infercnv_malignancy_classification_never_branches_on_treatment(self):
        # Direct treatment-blindness check for the malignancy-calling script
        # itself (raised by Codex review): "Control"/"Tamoxifen" must never
        # appear as literals anywhere in the script, and `condition` may
        # appear ONLY as a passive output-metadata field (the line building
        # the per-cell output data.frame), never inside reference-cell
        # selection, CNV scoring, seed selection, or thresholding logic.
        code_lines = _code_lines("gse245601_05_infercnv_malignant.R")
        for line in code_lines:
            assert "Control" not in line, f"{line!r} references treatment condition 'Control'"
            assert "Tamoxifen" not in line, f"{line!r} references treatment condition 'Tamoxifen'"
        condition_lines = [l for l in code_lines if "condition" in l and "conditionMessage" not in l]
        assert len(condition_lines) == 1
        assert "condition = sample_obj$condition" in condition_lines[0], (
            f"unexpected use of `condition` outside passive output-metadata construction: {condition_lines}"
        )


# --- Output-table structural tests (skip if not yet generated) --------------


class TestSampleManifestAndQCSummary:
    def test_qc_summary_has_20_primary_samples(self):
        df = _table("gse245601_qc_summary.tsv")
        assert len(df) == 20
        assert df["patient"].nunique() == 10

    def test_10_exact_control_tamoxifen_pairs(self):
        df = _table("gse245601_qc_summary.tsv")
        for patient, sub in df.groupby("patient"):
            assert sorted(sub["condition"]) == ["Control", "Tamoxifen"]

    def test_cells_after_qc_never_exceeds_cells_before(self):
        df = _table("gse245601_qc_summary.tsv")
        assert (df["n_cells_post_qc"] <= df["n_cells_raw"]).all()
        assert (df["n_cells_final"] <= df["n_cells_post_qc"]).all()


class TestCellMetadataFrozen:
    def test_unique_cell_ids_no_sample_label_collision(self):
        df = _table("gse245601_cell_metadata_frozen.tsv.gz")
        assert df["cell_id"].is_unique
        for _, row in df.head(2000).iterrows():
            assert row["cell_id"].startswith(f"{row['sample_id']}_")

    def test_required_metadata_columns_present(self):
        df = _table("gse245601_cell_metadata_frozen.tsv.gz")
        required = {
            "cell_id", "GSM", "patient", "condition", "sample_id", "seurat_cluster",
            "broad_cell_type", "is_epithelial", "cnv_score", "cnv_correlation_to_seed",
            "primary_malignancy_label", "sensitivity_malignancy_label",
        }
        assert required.issubset(set(df.columns))

    def test_malignancy_labels_restricted_to_allowed_values(self):
        df = _table("gse245601_cell_metadata_frozen.tsv.gz")
        allowed = {"malignant", "non-malignant epithelial"}
        observed = set(df["primary_malignancy_label"].dropna().unique())
        assert observed.issubset(allowed)

    def test_no_candidate_gene_columns_present(self):
        df = _table("gse245601_cell_metadata_frozen.tsv.gz")
        for gene in ALL_CANDIDATE_TERMS:
            assert gene not in df.columns


class TestPairEligibility:
    def test_eligibility_derived_only_from_malignant_cell_count(self):
        df = _table("gse245601_pair_eligibility.tsv")
        assert len(df) == 10
        for _, row in df.iterrows():
            expected = (
                pd.notna(row["n_malignant_control"])
                and pd.notna(row["n_malignant_tamoxifen"])
                and row["n_malignant_control"] >= row["min_required_per_arm"]
                and row["n_malignant_tamoxifen"] >= row["min_required_per_arm"]
            )
            assert bool(row["eligible_for_pseudobulk"]) == bool(expected)

    def test_min_required_per_arm_is_frozen_50(self):
        df = _table("gse245601_pair_eligibility.tsv")
        assert (df["min_required_per_arm"] == 50).all()


class TestScopeBoundary:
    def test_no_pseudobulk_output_table_exists(self):
        forbidden = [
            "gse245601_pseudobulk*.tsv", "gse245601_*_de.tsv", "gse245601_candidate_expression*.tsv",
            "gse245601_*wilcox*.tsv", "gse245601_*edger*.tsv", "gse245601_*deseq*.tsv",
        ]
        for pattern in forbidden:
            matches = list(TABLES_DIR.glob(pattern))
            assert matches == [], f"found forbidden output(s) for this phase: {matches}"

    def test_preanalysis_document_exists_and_predates_qc(self):
        doc_path = REPO_ROOT / "docs" / "gse245601_PREANALYSIS.md"
        assert doc_path.exists()
        text = doc_path.read_text()
        assert "QC_MIN_NCOUNT" not in text  # thresholds described in prose, not as code constants
        assert "5000" in text
        assert "2000" in text
        assert "25" in text
